#!/usr/bin/env python3

import click
import webview
import threading
from urllib import parse
import json


theme_file = '/home/sm/bin/bashrc_prompt.themes'
def get_themes():
    with open(theme_file) as f:
        j = f.read()
    p = parse.quote_plus(j)
    return p

def save_themes(data):
    with open(theme_file, 'w') as f:
        f.write(data)

class Api():
    theme_data = []

    def assemble(self):
        data = ':'.join(self.theme_data)
        data = json.dumps(json.loads(data), indent=2)
        save_themes(data)
        self.theme_data = []

    def save(self, data):
        if data == '<!END!>':
            self.assemble()
        else:
            self.theme_data.append(data)


def init():
    url = 'dist/index.html?data={}'.format(get_themes())
    api = Api()
    webview.create_window('Bash prompt customizer', url,
                          js_api=api, min_size=(600, 450), debug=True)


if __name__ == '__main__':
    init()
